name: Issue Comment Posted

on:
  issue_comment:
    types: [created]

jobs:
  self-assign:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          sparse-checkout: build_tools

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install PyGithub
        run: pip install -Uq PyGithub

      - name: Assign issue
        run: python build_tools/issue_assign.py
        env:
          CONTEXT_GITHUB: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
